# Generated by Django 4.2.2 on 2023-08-22 11:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='static/img/')),
                ('datatime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
