# Generated by Django 4.2.4 on 2023-08-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_me_email_contact_me_location_contact_me_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me',
            name='telephone',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
