# Generated by Django 4.2.2 on 2023-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_me_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=50)),
                ('image', models.ImageField(default=True, upload_to='')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
