# Generated by Django 4.2.2 on 2023-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_portfolio_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_me',
            name='category',
            field=models.BooleanField(max_length=50),
        ),
    ]
