# Generated by Django 4.2.2 on 2023-08-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_portfolio_me_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_me',
            name='category',
            field=models.FloatField(),
        ),
    ]
